### ISSUE TITLE
Nightly exports fail 1/3 times after INCEpTION upgrade

### ISSUE THREAD

**Issue by elizlee** [isi-vista/curated-training-annotator#112]
After upgrading INCEpTION to version [0.17.3](https://github.com/inception-project/inception/releases/tag/inception-app-0.17.3), the server became unreachable twice while the [nightly export](https://github.com/isi-vista/curated-training-annotator/blob/master/annotation-utils/src/main/java/edu/isi/vista/annotationutils/PushAnnotations.kt) ran -- this causes the program to continue sending requests resulting in HTTP failures as it attempts to read each project.

* Monday (3/1): Upgrade complete
* Tuesday (3/2): Inception unreachable with this error (from `inception.log`):
```
01:34:36.810 [http-nio-8080-exec-7] ERROR de.tudarmstadt.ukp.clarin.webanno.webapp.remoteapi.aero.AeroRemoteApiController - Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: Java heap space
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: Java heap space
```
* Wednesday (3/3): Export complete
* Thursday (3/4): Export complete
* Friday (3/5): Inception unreachable with this error (from `inception.log`):
```
Exception in thread "http-nio-8080-ClientPoller" 01:04:44.642 [http-nio-8080-exec-7] ERROR de.tudarmstadt.ukp.clarin.webanno.webapp.remoteapi.aero.AeroRemoteApiController - Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: GC overhead limit exceeded
```

I restarted INCEpTION both times to regain access. The app otherwise runs fine, albeit rather slowly. There are still 30 GB of free space on the machine, so it doesn't seem like we're running out of space for annotation data.

After monitoring Inception for a few days, I noticed that the amount of memory used increases after every export, then lets go of the extra memory after being restarted. It normally uses around 20 GB and tends to stall if it uses more than 40, which usually happens on the third export run. It seems like either there's a memory leak somewhere that deals with project exports or garbage collection is not happening when it should.

**Comment by reckart** [comment]
Version 0.17.3 or 0.18.3 (latest)?

**Comment by reckart** [comment]
We fixed a memory leak in 0.18.1, but that one should only affect 0.18.0 and not earlier releases. 

If you could configure a heap dump on OOM (`-XX:+HeapDumpOnOutOfMemoryError`) we could probably figure out potential leaks.

**Comment by elizlee** [comment]
@reckart -- 0.17.3

**Comment by reckart** [comment]
Ok. Please check the release notes of the latest INCEpTION releases - we fixed some pretty critical bugs that could potentially lead to loss of annotations.

**Comment by elizlee** [comment]
> If you could configure a heap dump on OOM (-XX:+HeapDumpOnOutOfMemoryError) we could probably figure out potential leaks.

@reckart -- I'm planning an upgrade to 19.0 for this weekend. In the meantime, I ran the resulting heap dump (from INCEpTION 0.17.3) through an analyzer, and it gave me one suspect:
```
1,866 instances of "de.tudarmstadt.ukp.clarin.webanno.api.dao.casstorage.CasHolder", loaded by "org.springframework.boot.loader.LaunchedURLClassLoader @ 0xc4f11a88" occupy 624,042,912 (81.26%) bytes.

Biggest instances:

de.tudarmstadt.ukp.clarin.webanno.api.dao.casstorage.CasHolder @ 0xe8ea3828 - 28,708,632 (3.74%) bytes.
These instances are referenced from one instance of "java.util.concurrent.ConcurrentHashMap$Node[]", loaded by "<system class loader>", which occupies 1,077,488 (0.14%) bytes.

Keywords
de.tudarmstadt.ukp.clarin.webanno.api.dao.casstorage.CasHolder
org.springframework.boot.loader.LaunchedURLClassLoader @ 0xc4f11a88
java.util.concurrent.ConcurrentHashMap$Node[]
```
If you would like to review the .hprof file yourself, I can share it with you.

**Comment by reckart** [comment]
If you have a good **confidential/secure** way of sharing the file, it could be insightful. 

600MB of CASes cached in memory sounds pretty ok, in particular if you run with `-Xmx40g` (40 gigs of heap). 
How large is the heap dump file that you have?

**Comment by elizlee** [comment]
@reckart -- It's 1.2GB; 160MB when compressed

**Comment by reckart** [comment]
That's a far cry from 40G. 

So you pass "-Xmx40g" to the Java process when you run it, right? And the host you run it on has >40GB of RAM?

**Comment by elizlee** [comment]
@reckart -- I don't pass that option to the Java process, but I realize I made a different mistake: the "40" it uses is the _percent_ of memory, not GB. It looks something like this around the time it throws the OutOfMemoryError:

```
PID	USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
9415 	www-data  20   0 3837196   1.5g   7680 S 132.8 40.3   2654:17 java
```

These are the stats right now, a few days after the latest reset (no exports attempted since):
```
KiB Mem :  3880644 total,   828688 free,  1388840 used,  1663116 buff/cache
KiB Swap:  8388604 total,  8142024 free,   246580 used.  2150496 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
19676 www-data  20   0 3787636 995252  13860 S 100.0 25.6   7370:43 java
```

**Comment by reckart** [comment]
Recent versions of inception show the max application memory on Startup. I'm not sure if 0.17.x already does that.

**Comment by elizlee** [comment]
Does it use the default MaxHeapSize when not declared? If that's the case, it would be about 994MB on our system.

**Comment by reckart** [comment]
The memory size is something that the JVM determines - INCEpTION cannot influence it.

[Here](https://stackoverflow.com/a/43368676/2511197) are some tips how to check the default sizes.

If the MaxHeapSize that shows up for you there is ~1GB, then that's probably the default.

Mind that a JVM needs more memory than just the heap. If you have a machine with 4 GB of main RAM, you could probably get away allocating 2 GB of that memory to the Java heap - assuming that you also need to run the OS, the database server, etc. If you can, I'd suggest you up you memory size a bit to 8 or 16 GB and then run INCEpTION with 6 or 10 GB of heap.

**Comment by reckart** [comment]
In 0.19.1, I'll add some parameters to tune the CAS cache size and also reduce the default in-memory cache size.

**Comment by reckart** [comment]
https://github.com/inception-project/inception/pull/2139

**Comment by reckart** [comment]
0.19.1 is out and tries to use smaller in-memory caches on machines with less memory.

You can also tune the cache using new properies for CAS cache documented in the admin docs.

**Comment by elizlee** [comment]
@reckart -- Thanks, that sounds great! I will plan to upgrade to 0.19.1 this weekend.

**Comment by elizlee** [comment]
Closing (at least for now) since things seem to be running smoothly again after
1. Setting the max heap size to 2GB
2. INCEpTION 0.19.1 upgrade

(Thank you again, @reckart!)
