### ISSUE TITLE
Export JSON annotations to git repository

### ISSUE THREAD

**Issue by rgabbard** [isi-vista/curated-training-annotator#30]

**Comment by berquist** [comment]
@rgabbard Does this also include the full documents themselves?

**Comment by berquist** [comment]
This should also be done automatically; a `cron` job on the server is probably sufficient. I'm assuming the exports can be done from the command line.

**Comment by rgabbard** [comment]
This is a start: https://github.com/isi-vista/curated-training-annotator/blob/master/annotation-utils/src/main/java/edu/isi/vista/annotationutils/ExportAnnotations.kt

The default JSON format does include the full document text - we may want to replace it with `__DOCUMENT_TEXT_REDACTED_FOR_IP_REASONS__` for something so we can freely distribute the JSON on GitHub

**Comment by berquist** [comment]
It sounds like the `curated-training-annotations` repo should contain the unredacted JSON export, and we can have a script in this repo that strips the full document text for putting the redacted annotations in a public repo.

**Comment by rgabbard** [comment]
Well, there are two options:

(1) we could have both a public and private version of the `curated-training-annotations` repo and do the stripping when we go from one to another
(2) we could just have the `ExportAnnotations` program do the stripping and go directly to `curated-training-annotations`.

(2) is probably simpler; we don't need the original text because it is entirely reproducible from the LDC releases.

**Comment by berquist** [comment]
Ok, going with (2) makes the release easier, but changes what we will have to do for the ingester (I don't know what the LDC releases are).

**Comment by rgabbard** [comment]
@berquist : Poke me tomorrow to write up the LDC releases. I think what we want is a script which, given the LDC releases and the document-text-less "de-hydrated" annotation, will "rehydrate" it to restore the document text.

**Comment by berquist** [comment]
That is more like (1), which I had suggested we do because it would probably be easier to ingest doc text + annotations simultaneously.

**Comment by rgabbard** [comment]
The difference is mostly with respect to Github repos and automation. In this proposal we go `Inception server ----cron----> dehydrated public GitHub ---internal-or-external-user-runs-scripts --> re-hydrated private copy for training`.   In (1) we go 

```
Inception server 
          |
      cron
         |
        v
hydrated private GitHub    ----> ISI internal training
        |
   another cron
       |
      v
  dehydrated public GitHub .  ----> external user is sad
```
