### ISSUE TITLE
Ingest curated training annotations into VistaNLP

### ISSUE THREAD

**Issue by berquist** [isi-vista/curated-training-annotator#31]
For each rehydrated JSON annotation in the export, create a VistaNLP document, which will require writing an ingester that implements [`AbstractIngester`](https://github.com/isi-nlp/isi-flexnlp/blob/de5ce82c4cdac507ca382fab91675749f389b204/flexnlp/model/pipeline.py#L169). This will read in the fields from each JSON file and eventually have the different theories attached to it (token, sentence, `CuratedTrainingAnnotation`).

(This means we will end up only scoring documents that have annotations, since the documents are attached to each annotation.)

**Comment by berquist** [comment]
An example of a pipeline that reads in raw input files and converts them to VistaNLP documents is https://github.com/isi-vista/gaia-event-extraction/blob/f3ce53daaebf17cc4decc7abf7cfc876ee14e9ac/gaia_event_extraction/model_data_utils.py#L76.

**Comment by berquist** [comment]
As I mentioned to @qpwo it might make more sense to have this live in https://github.com/isi-vista/gaia-event-extraction, closer to the model training and evaluation code.

**Comment by berquist** [comment]
Something that occurred to me yesterday as we were working on the ingester: the workflow we were testing, with each annotation leading to a single VistaNLP document each, is not going to work. This will lead to duplicate documents.
- Make a parameter that takes a path to a file, itself containing a list of full paths to each rehydrated JSON annotation.
- Take this list and create a mapping between the original document ID and the filenames for each annotation on that document ID.
- For each document ID,
  - Load the JSON for each of the annotations
  - Make sure that the raw source text is consistent between all the annotations

We can do something similar to the `ApfIngester` where the raw text and annotation files (if present) are kept together using the `ApfIngesterInput` data class, having something like `CuratedTrainingJsonIngesterInput` that keeps all the JSON annotation paths together. So that no one else has to write processing boilerplate in the future, it should take the filenames (not the mapping) to all annotations for the same document, load them with `json.loads`, and perform the consistency check before passing to the `CuratedTrainingJsonIngester`.

**Comment by qpwo** [comment]
I hadn't realized there would be dups. Maybe we should not use [Rehydrate.kt](https://github.com/isi-vista/curated-training-annotator/blob/30-export-json-dehydrated/annotation-utils/src/main/java/edu/isi/vista/annotationutils/Rehydrate.kt) then. The ingester itself could also fetch the full text from the database. The json directories and filenames and docIDs are quite structured and consistent, so everything can be done procedurally without storing maps, like [here](https://github.com/isi-vista/curated-training-annotator/blob/5ea83801d0345d3e173cba5a067370e550bedd3b/annotation-utils/src/main/java/edu/isi/vista/annotationutils/Rehydrate.kt#L69)...
