### ISSUE TITLE
Create Inception configuration for annotating the Conflict.Attack event

### ISSUE THREAD

**Issue by rgabbard** [isi-vista/curated-training-annotator#5]
We need to be able to annotate the following sorts of spans:

* that a span of text (e.g. a sentence) contains a `Conflict.Attack` event
* that following argument spans, which should be attachable to `Conflict.Attack` events:
   * `Attacker`, `Target`, `Place`, `Time`, `Instrument`
* that a span of text (e.g. a sentence) is `negative` for a `Conflict.Attack` event
* that a span of text is a trigger for a `Conflict.Attack` event (this should attach like an argument, although it is distinct)
* that a span of text is `interesting`. This doesn't need to attach to a particular event.

**Comment by shinyichen** [comment]
This is the exported file for the configuration. Please check if it is correct. 
[typesytem.xml.zip](https://github.com/isi-vista/curated-training-annotator/files/2673179/typesytem.xml.zip)

To import it into a project in Inception, go to admin and project's Layers tab. Use Import Layers.

**Comment by shinyichen** [comment]
This is the exported file for the configuration. Please check if it is correct.
[typesytem.xml.zip](https://github.com/isi-vista/curated-training-annotator/files/2673205/typesytem.xml.zip)

To import it into a project in Inception, decompress the file, go to admin and project's Layers tab. Use Import Layers.

**Comment by shinyichen** [comment]
Previously when I exported all layers, granularity information was not exported. To keep that information I had to export the layers individually. The attached file contains the different layers exported.
[conflict.layers.zip](https://github.com/isi-vista/curated-training-annotator/files/2691657/conflict.layers.zip)

**Comment by rgabbard** [comment]
@shinyichen : Can you make a list of steps to reproduce this bug and file it on Inception?

**Comment by reckart** [comment]
The UIMA type system export is limited - it does not preseve all information. This is not a bug - it is due to the fact that INCEpTION has options that UIMA does not have (and vice versa). I suppose you'd like to have a "JSON (all layers)" export option?

**Comment by reckart** [comment]
Note: the JSON format does preserve all info.

**Comment by rgabbard** [comment]
@reckart : Got it. An `JSON (all layers)` export option would be nice but isn't high priority for us (it's easy enough just to make a note to fix the granularities when importing a setup).

**Comment by shinyichen** [comment]
Following @reckart's suggestion.
[Conflicts_project.zip](https://github.com/isi-vista/curated-training-annotator/files/2692384/Conflicts_project.zip)
