### ISSUE TITLE
Log external searches

### ISSUE THREAD

**Issue by rgabbard** [isi-vista/curated-training-annotator#7]
What would we need to do to produce some sort of log of what external searches were performed by what user at what time?  This is important for writing a paper about the approach.

**Comment by Rentier** [comment]
INCEpTION out of the box already logs many things. e.g. annotation actions, changes in project configurations and so on. These are saved in the database of INCEpTION and allow researchers detailed analysis of their annotation experiments. The right now implemented logged events can be found in the `log` packages of the respective modules, e.g. for the internal search, it can be found under https://github.com/inception-project/inception/blob/master/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/log/ .

What you need to do to log new events, e.g. external search queries:

1. Define a Spring event that you want to log. It needs to extend `ApplicationEvent`, e.g.  https://github.com/inception-project/inception/blob/6b571bf802e3d1ad2ddbf33d1fb655b874792f0b/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/event/SearchQueryEvent.java
2. Publish the event at the appropriate time and place, e.g. https://github.com/inception-project/inception/blob/fe9afb45f977db118f7136fe58aa2891d4470a62/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java#L156
3. Define an `EventLoggingAdapter`. This is the bridge between the events and the logging subsystem of INCEpTION. It takes the event(s) of interest and saves it in the database. To continue the example, see e.g. https://github.com/inception-project/inception/blob/6b571bf802e3d1ad2ddbf33d1fb655b874792f0b/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/log/SearchQueryEventAdapter.java . The event payload is saved as JSON next to its metadata in the database.

**Comment by rgabbard** [comment]
Thanks - this is very helpful

**Comment by shinyichen** [comment]
Made a pull request
https://github.com/isi-vista/inception-very-large-corpora-old/pull/3

**Comment by rgabbard** [comment]
This is stored in the DB.  Here is an example:
```
| 267 | ExternalSearchQueryEvent       | 2019-03-26 09:58:07 | admin             | {"query":"\"known for\""}                                                                                                                                                                      |       1 |       -1 | admin             |
```

from `SELECT * FROM logged_event ORDER BY created`
