### ISSUE TITLE
Missing or unnecessary annotation times

### ISSUE THREAD

**Issue by elizlee** [isi-vista/curated-training-annotator#86]
As observed from the current daily HTML output, there are a few issues to work out regarding `ParseEventLogs` or `ExtractAnnotationStats`.

1. Several projects are not listed. We want to figure out why this is and fix it.
2. A handful of projects with annotations have a total annotation time of 0. We want to make sure that this only happens because the actions for this project had long enough time gaps that they exceeded the threshold for being recorded.
3. Projects that we are not concerned about are listed (e.g. sandbox, copy_of). We would like to remove these stats to clear clutter.

**Comment by elizlee** [comment]
Some projects are not getting their event logs downloaded. Are they only downloaded on days when the project is updated? If so, I'll have to change this.

**Comment by elizlee** [comment]
It turns out that it's not a matter of when it is updated. The projects with this issue appear to share one thing in common: they have a relatively large number of documents.

The error message after attempting to export such projects is `Read timed out`, so this further suggests that the large size of the projects are preventing these exports. Increasing the read timeout seems to resolve this issue.

**Comment by elizlee** [comment]
Annotated projects with zero annotation time:
* `gabbard`'s projects have no recorded time because the script checks that each action's user is the same as the project's, and "admin" != "gabbard". No issue to address here since we're not concerned with these projects.
* Two of `tyler_worthy`'s projects and one of `yelena`'s only have one action recorded in the log - the one indicating that the project was created - despite having multiple annotated documents. This unfortunately appears to be a result of the [tag addition](https://github.com/isi-vista/curated-training-annotator/pull/89) - even though the original `event.log` files were imported along with the modified copies, they must have been overwritten by the Inception app. I do have the originals saved elsewhere, but perhaps figuring out how to accommodate those logs should be a separate issue.
* `russian-Transaction.Transaction.EmbargoSanction-yelena` also has annotations but no recorded time. This particular project only had one annotated document, and thanks to this issue, I saw that `parseProjectEvents` does not actually record the time for the latest annotated document. I will fix this next.

**Comment by reckart** [comment]
There have been some improvements to import/export speed in recent versions of INCEpTION. Which version are you using?

**Comment by elizlee** [comment]
@reckart -- We're using 0.15.2

**Comment by reckart** [comment]
INCEpTION 0.16.1 includes [improvements](https://github.com/webanno/webanno/issues/1690) to speed up the import/export of large projects.
