### ISSUE TITLE
Add new argument tags to existing Inception projects

### ISSUE THREAD

**Issue by elizlee** [isi-vista/curated-training-annotator#88]
We would like to be able to add new sets of tags to existing projects without having to add them manually (which would be extremely tedious depending on how many projects must be modified). For example, an ontology extension gives all `Life.Die(.subtype)` event types a `Killer` argument role, so all applicable projects will need a `Killer` tag added if it doesn't have one already.

Since the Inception application doesn't appear to allow mass tag addition, I thought of this plan which uses the remote API:
1. **Export and save** all relevant project files (e.g. all `Life.Die` projects).
2. Create modified copies of these ZIP archives such that for each `.json` project file, **add the new tags** for that event type (e.g. add `Killer` to `tag_set[tags]`).
3. We want to import these modified projects without creating a bunch of `copy_of` projects, which is what Inception automatically does to prevent projects from being overwritten (and this doesn't appear to be configurable), so **delete** each project from Inception that was successfully modified locally.
4. For each modified project, **import** these to Inception.

**Comment by elizlee** [comment]
I am writing and testing the above steps in this order: 1, 2, 4, 3. I have completed 1 and 2, which creates projects with new tags that can be imported manually if needed, but I am stuck on step 4. This is the code that I recently tried using to test the import functionality:
```
val importUrl = "$inceptionUrl/api/aero/v1/projects/import"
ZipFile(exportInMemoryZip).use {
                retryOnFuelError {
                    importUrl.httpPost(
                            parameters = listOf("file" to it)
                    )
                            .authenticateToInception()
                            .resultObjectThrowingExceptionOnFailure<AeroResult<Project>>(mapper)
                            .body
                }
            }
```
where `exportInMemoryZip` is the in-memory ZIP file exported from Inception. However, even though I've tried importing the same file in different formats (`File`, `Path`), I get `com.github.kittinunf.fuel.core.BubbleFuelError: HTTP Exception 415`. I also tried specifying the content type:
```
...
importUrl.httpPost(
                            parameters = listOf("file" to it)
                    )
                            .header(Headers.CONTENT_TYPE, "application/json")
                            .authenticateToInception()
...
```
but this gives me an `HTTP Exception 400` instead.

@gabbard : Do you happen to have any insight on what I am doing wrong here?

**Comment by gabbard** [comment]
@elizlee : Does Inception have anything informative in its error log?  HTTP 400 is "Bad request", which suggests it is rejecting your request for some reason.

**Comment by elizlee** [comment]
@gabbard : The most relevant thing I can find is this:
```
05:30:05.763 [http-nio-8080-exec-1371] ERROR de.tudarmstadt.ukp.clarin.webanno.w
ebapp.remoteapi.aero.AeroRemoteApiController - Channel not open for writing - ca
nnot extend file to required size
java.io.IOException: Channel not open for writing - cannot extend file to requir
ed size
        at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:898) ~[?:1.8.0_22
2]
        at sun.nio.ch.FileChannelImpl.transferFromFileChannel(FileChannelImpl.ja
va:631) ~[?:1.8.0_222]
        at sun.nio.ch.FileChannelImpl.transferFrom(FileChannelImpl.java:702) ~[?
:1.8.0_222]
        at org.apache.commons.io.FileUtils.doCopyFile(FileUtils.java:1131) ~[com
mons-io-2.6.jar!/:2.6]
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1076) ~[commo
ns-io-2.6.jar!/:2.6]
        at org.apache.commons.io.FileUtils.copyFileToDirectory(FileUtils.java:10
00) ~[commons-io-2.6.jar!/:2.6]
        at org.apache.commons.io.FileUtils.copyFileToDirectory(FileUtils.java:96
1) ~[commons-io-2.6.jar!/:2.6]
        at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.exporters.Annotation
DocumentExporter.exportAnnotationDocumentContents(AnnotationDocumentExporter.jav
a:249) ~[webanno-api-dao-4.0.0-beta-12.jar!/:?]
        at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.exporters.Annotation
DocumentExporter.exportData(AnnotationDocumentExporter.java:123) ~[webanno-api-d
ao-4.0.0-beta-12.jar!/:?]
        at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportService
Impl.exportProject(ProjectExportServiceImpl.java:222) ~[webanno-api-dao-4.0.0-be
ta-12.jar!/:?]
...
```
but it seems more likely to be from the export errors that occurred last night.

Here's an extended traceback, if it's helpful:
```
14:42:55.531 [main] WARN  mu.KLogging - com.github.kittinunf.fuel.core.BubbleFuelError: HTTP Exception 400 
	com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:84)
	com.github.kittinunf.fuel.core.DeserializableKt.response(Deserializable.kt:168)
	edu.isi.vista.annotationutils.TestAddNewTagsKt$main$$inlined$use$lambda$1.invoke(TestAddNewTags.kt:323)
	edu.isi.vista.annotationutils.TestAddNewTagsKt$main$$inlined$use$lambda$1.invoke(TestAddNewTags.kt)
	edu.isi.vista.annotationutils.ExportAnnotationsKt.retryOnFuelError(ExportAnnotations.kt:259)
	edu.isi.vista.annotationutils.ExportAnnotationsKt.retryOnFuelError$default(ExportAnnotations.kt:256)
	edu.isi.vista.annotationutils.TestAddNewTagsKt.main(TestAddNewTags.kt:187)
Caused by: com.github.kittinunf.fuel.core.BubbleFuelError: HTTP Exception 400
...
```

**Comment by gabbard** [comment]
huh - when you try to run this, does the log register anything at all?

**Comment by elizlee** [comment]
I don't think it does; this is the last item it logged:
```
06:51:40.949 [http-nio-8080-exec-1402] ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] - Session event listener threw exception
java.lang.NullPointerException: null
```

**Comment by gabbard** [comment]
Huh - does that timestamp seem to correspond with your last request or not?

**Comment by elizlee** [comment]
No - I ran it again and checked, and the error and timestamp are the same

**Comment by gabbard** [comment]
Do we have other code which uploads projects you can point em to as an example?

**Comment by elizlee** [comment]
None that I can find

**Comment by gabbard** [comment]
Is it possible it is unhappy because we are trying to upload a project which already exists?

**Comment by elizlee** [comment]
@gabbard : There's something new in the logs (I'm guessing sometime around 4:30 ET)
```
13:29:19.089 [http-nio-8080-exec-1432] ERROR org.apache.catalina.core.ContainerB
ase.[Tomcat].[localhost].[/].[dispatcherServlet] - Servlet.service() for servlet
 [dispatcherServlet] in context with path [] threw exception
org.springframework.security.web.firewall.RequestRejectedException: The request
was rejected because the URL contained a potentially malicious String ";"
        at org.springframework.security.web.firewall.StrictHttpFirewall.rejected
BlacklistedUrls(StrictHttpFirewall.java:369) ~[spring-security-web-5.2.2.RELEASE
.jar!/:5.2.2.RELEASE]
        at org.springframework.security.web.firewall.StrictHttpFirewall.getFirew
alledRequest(StrictHttpFirewall.java:336) ~[spring-security-web-5.2.2.RELEASE.ja
r!/:5.2.2.RELEASE]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(Fi
lterChainProxy.java:194) ~[spring-security-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE
]
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChai
nProxy.java:178) ~[spring-security-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
```

**Comment by gabbard** [comment]
@gabbard : Is this consistently produced when you try this operation? Or was it perhaps just produced by something else an annotator did?

**Comment by elizlee** [comment]
> Is it possible it is unhappy because we are trying to upload a project which already exists?

I deleted the dummy project and tried again, but I get the same error, so that doesn't seem to be the problem.

**Comment by elizlee** [comment]
> Is this consistently produced when you try this operation? Or was it perhaps just produced by something else an annotator did?
It may have been caused by something else, especially since the timestamps don't sync with my import attempts.

**Comment by elizlee** [comment]
Trying to upload the modified copy and changing the content type to `application/json;charset=UTF-8`, I get this response:
```
19:09:54.207 [main] INFO  mu.KLogging - <-- 415 http://curatedtraining.isi.edu:8080/api/aero/v1/projects/import?file=%5BB%4015ff3e9e
Response : 
Length : -1
Body : (unknown number of bytes of application/json;charset=UTF-8)
Headers : (10)
Cache-Control : no-cache, no-store, max-age=0, must-revalidate
Connection : keep-alive
Date : Mon, 20 Jul 2020 23:09:54 GMT
X-XSS-Protection : 1; mode=block
Expires : 0
X-Content-Type-Options : nosniff
Content-Type : application/json;charset=UTF-8
Pragma : no-cache
X-Frame-Options : DENY
Keep-Alive : timeout=60
```
